services:
  - type: web
    name: eee-backend
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential gcc g++ libblas-dev liblapack-dev libopenblas-dev && \
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/cache
