services:
  - type: web
    name: eee-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: python app.py
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/cache
