services:
  - type: web
    name: eee-backend
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential gcc libblas-dev liblapack-dev && \
      python -m pip install --upgrade pip setuptools wheel && \
      pip install --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/cache
