services:
  - type: web
    name: eee-backend
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel && \
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/cache
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: HF_MODEL_ID
        value: Thiyaga158/Distilbert_Ner_Model_For_Email_Event_Extraction
      - key: HUGGINGFACE_API_TOKEN
        sync: false
